server:
  port: 3000
  servlet:
    context-path: /api


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/library
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  graphql:
    cors:
      allowed-origins: "*"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true

# mybatis-plus的配置
mybatis-plus:
  type-aliases-package: com.library.pojo
  global-config:
    db-config:
      logic-delete-field: isDeleted
      id-type: auto
  configuration:
    map-underscore-to-camel-case: false

jwt:
  token:
    tokenExpiration: 120
    tokenSignKey: library123
